heat_template_version: 2013-05-23

parameters:
  key_name:
    type: string
    description: Name of keypair to assign to server
    default: yonida
  image:
    type: string
    description: Name of image to use for server
    default: centos7
  flavor:
    type: string
    description: Flavor to use for server
    default: m1.tiny
  timeout:
    type: number
    description: Timeout for WaitCondition, depends on your image and environment
    default: 800
  numLots:
    type: number
    description: number of images per lot
    default: 60
  indexList:
    type: comma_delimited_list
    label: start index of lots
    default: "1"
  numberLots:
    type: number
    label: number of lots
    default: 1

resources:
  wait_condition:
    type: OS::Heat::WaitCondition
    properties:
      handle: {get_resource: wait_handle}
      # Note, count of 5 vs 6 is due to duplicate signal ID 5 sent below
      count: {get_resource: numberLots}
      timeout: {get_param: timeout}

  wait_handle:
    type: OS::Heat::WaitConditionHandle

  repeat:
    for_each:
      <%index%>: {get_param: indexList}
    template:
      povray<%index%>:
        type: OS::Nova::Server
        properties:
          image: {get_param: image}
          flavor: {get_param: flavor}
          key_name: {get_param: key_name}
          user_data_format: RAW
          user_data:
            str_replace:
              template: |
                #!/bin/sh
			#Proxy config
                export http_proxy=http://proxy.clermont-universite.fr:8080
			#openstack install
                apt-get -y install python-openstackclient
                #openstack config
                export OS_AUTH_URL=http://172.20.88.10:5000/v3
                export OS_PROJECT_ID=72fe25d80014433f8bc78a734a5be70b
                export OS_PROJECT_NAME="yonidabrah"
                export OS_USER_DOMAIN_NAME="Default"
                export OS_USERNAME="yonidabrah"
                export OS_PASSWORD="Ent12345"
                export OS_REGION_NAME="RegionOne"
                export OS_INTERFACE=public
                export OS_IDENTITY_API_VERSION=3            
                #Test Config
                openstack server list
                #Get zzpovray.tar.gz from container
                openstack object save povrayContainer zzpovray.tar.gz
                #Extract povray
                tar xfv zzpovray.tar.gz
                ls -l
                cd  povray
                #Creating images
                ./povray +A +W800 +H600 +Lshare/povray-3.6/include/ +SF`ind` +EF`ind + nmLot`  glsbng.ini
                #Upload images to container
                openstack object create povrayContainer *.png
                wc_notify --data-binary '{"status": "SUCCESS"}'
                #Shutdown instance
                shutdown
              params:
                wc_notify: { get_attr: ['wait_handle', 'curl_cli'] }
                ind: <%index%>
                nmLot: {get_param: numLots}

  genGifInstance:
    type: OS::Nova::Server
    depends_on: wait_condition
    properties:
      image: {get_param: image}
      flavor: {get_param: flavor}
      key_name: {get_param: key_name}
      user_data_format: RAW
      user_data:
        str_replace:
          template: |
            #!/bin/sh
            export http_proxy=http://proxy.clermont-universite.fr:8080
            apt-get -y install python-openstackclient
            #openstack config
            export OS_AUTH_URL=http://172.20.88.10:5000/v3
            export OS_PROJECT_ID=72fe25d80014433f8bc78a734a5be70b
            export OS_PROJECT_NAME="yonidabrah"
            export OS_USER_DOMAIN_NAME="Default"
            export OS_USERNAME="yonidabrah"
            export OS_PASSWORD="Ent12345"
            export OS_REGION_NAME="RegionOne"
            export OS_INTERFACE=public
            export OS_IDENTITY_API_VERSION=3
            #Test Config
            openstack server list
            #install ImageMagick
            apt-get -y install imagemagick
            #Get images from container
            openstack container save povrayContainer
            #Create GIF file
            convert *.png -delay 6 -quality 100 glsbng.gif
		 #Upload GIF file to povrayContainer
            openstack object create povrayContainer glsbng.gif
		 #Shutdown instance
            shutdown
          params:
            wc_notify: { get_attr: ['wait_handle', 'curl_cli'] }

outputs:
  curl_cli:
    value: { get_attr: ['wait_handle', 'curl_cli'] }
  wc_data:
    value: { get_attr: ['wait_condition', 'data'] }

